### ISSUE TITLE
Remove Duplicate of Webhelper

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper-navigation#1]
Currently the WebHelper is simply copied from GraphHopper with [the precision change](https://github.com/graphhopper/graphhopper/pull/1422/files#diff-8d08370658d986ae9bb97143e0e9d931R108).

We need to commit the changed file to GraphHopper and remove the duplicate here, or, we keep a modified version of the encode polyline function here. WDYT @karussell should I create a new PR containing only the precision change?

**Comment by karussell** [comment]
Yes, please consider a PR making the encoding more flexible.
