### ISSUE TITLE
Use heading for route calculation

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper-navigation#11]
Mapbox allows to pass a so called bearings object to the api, which works similarly to our heading parameter.

`/13.43,52.51;13.42,52.5;13.43,52.5?bearings=60,45;;45,45`

Every bearing contains of `{angle, degrees}`. Currently our core only allows to use angles and doesn't allow to specify the degrees (as in how big of a degree is allowed). Values can be skipped by passing empty `;;`, but the number of bearings must match the number of waypoints.

**Comment by karussell** [comment]
Here we only need the first value after we know the last few points. For the other entries we could specify pass_through=true.

**Comment by boldtrn** [comment]
> pass_through=true

Yes, but pass_through is a different story again :). The Mapbox API has a similar parameter called `continue_straight`. This is similar to pass_through. We can also add continue_straight :).

BTW: [continue_straight] "Defaults to  true for  mapbox/driving and  false for  mapbox/walking and  mapbox/cycling"

**Comment by karussell** [comment]
Ok. I just meant that we do not need or know heading for the via-points, only for the first point I think. (Except we do some more complicated analysis we could calculate a heading to deliver only on the right side of the road ;) if this is a preference of the driver)

**Comment by boldtrn** [comment]
> Ok. I just meant that we do not need or know heading for the via-points, only for the first point I think. 

Yes sure, but if we do it for one point, we can just do it for all points :). The core supports it and the Mapbox SDK supports it. Implementation wise I don't expect the workload to be different?

> heading to deliver only on the right side of the road ;) if this is a preference of the driver

Actually Mapbox has a parameter for this. 

`approaches`

> A semicolon-separated list indicating the side of the road from which to approach waypoints in a requested route. Accepts  unrestricted (default, route can arrive at the waypoint from either side of the road) or  curb (route will arrive at the waypoint on the  driving_side of the region). ...
