### ISSUE TITLE
Rename /mapbox endpoint

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-navigation#15]
Rename endpoint and maven artifact.

Other options that avoid copyrighted words:

 * `/mb` or `/mpbx`
 * `/navigation`
 * `/navigate` (better fit to `/route`)
 * `/directions`

It should not go under `/route` like `/route/navigation` as it is something completely different. Also `/osrm` is not correct as we want to make the mapbox Nav SDK working where osrm endpoint does not help.

**Comment by boldtrn** [comment]
> and maven artifact

How should we name the maven artifact?

My initial idea was to have the option to add support for multiple navigation sdks in the future, this could be complicated when renaming the endpoint to `/navigate`. When we add another navigation sdk, it might be a bit complicated to understand which endpoint belongs to which sdk.

**Comment by karussell** [comment]
I doubt that we'll ever have the resources to support more than one SDK at a time. So even if another SDK will be used we will deprecate the current one and e.g. move forward with a different version. So I propose to just have one artifact `graphhopper-navigation` without a parent.

**Comment by boldtrn** [comment]
Ok makes sense as well, I will create PR :)
