### ISSUE TITLE
Maneuver "arrive" not generated

### ISSUE THREAD

**Issue by stoefln** [graphhopper/graphhopper-navigation#22]
I noticed that the converted response does not include an "arrive" maneuver. Is there a reason or am I missing something?
Testing the converter with the current mapbox navigation demos, I see some issues. That made me wonder how complete this implementation actually is...?

**Comment by karussell** [comment]
> I noticed that the converted response does not include an "arrive" maneuver.

It should. Or what do you think, @boldtrn ?

> I see some issues.

Which one?

> how complete this implementation actually is...?

Not a fully complete thing but works already

**Comment by boldtrn** [comment]
Could you provide an example route that misses the arrive maneuver? I just double checked a random example and it contains:
```json
"maneuver": {
"bearing_after": 0,
"bearing_before": 0,
"location": [
1
1,
],
"type": "arrive",
"instruction": "arrive at destination",
},
```

> That made me wonder how complete this implementation actually is...?

We skipped some things, especially annotations and intersections, so it's not complete. Some fields like `bearing_before` and `bearing_after` do have a fixed value. Our goal was to provide the minimal set of information that allows proper navigation and is compatible with the SDK. Please let us know if your clients need something else, we can always add more features if needed.

**Comment by stoefln** [comment]
Thanks for the quick response!
I just figured, that "arrive" should be actually generated. Will check my codebase for the problem. Might be related to the fact that I am using graphhopper 0.82 instead of 0.11

> I see some issues.
When I mock the route ride (with ReplayRouteLocationEngine), the replay gets stuck at some point. Usually like one or two steps from the destination

**Comment by boldtrn** [comment]
> When I mock the route ride (with ReplayRouteLocationEngine), the replay gets stuck at some point. Usually like one or two steps from the destination

I have seen this issue sometimes. It should happen less with #21 but it might still happen, also see https://github.com/graphhopper/graphhopper-navigation-android/issues/1. I think is an issue of the simulator. If you mock your GPS location for example with [this app](https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito) it works fine.

**Comment by stoefln** [comment]
Couldn't it be related to the fact that I am missing the arrive instruction?
I guess you are not supporting graphhopper 0.82, but maybe you can help me out anyway: Is it possible, that GH 0.82 is the reason why I can't find any arrival step in the GH response?
See response here: https://gist.github.com/stoefln/32a47f5b91f1d429967555006e3666a5
And resulting mapbox data here: https://gist.github.com/stoefln/b5b087133a41e92601717cc5390d7ab4

**Comment by boldtrn** [comment]
Ah now I see, there is no arrive / finish instruction in your GraphHopper instructions. The converter only converts your GraphHopper instructions it won't add instructions. So this issue seems to be related to your codebase. Probably it's not related to GH 0.82, IIRC there should be a finish instruction in 0.82.

**Comment by stoefln** [comment]
Found some issue with the web API we are using. Thanks a lot for your help!
