### ISSUE TITLE
Cannot fetch best response if list is empty

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-navigation#29]
```
curl 'https://graphhopper.com/api/1/navigate/directions/v5/gh/cycling/5.711217,45.180396;11.255955,43.770625?overview=full&roundabout_exits=true&bearings=307.597076%2C90%3B&annotations=congestion%2Cdistance&voice_instructions=true&steps=true&geometries=polyline6&alternatives=true&banner_instructions=true&voice_units=metric&vehicle=bike&access_token=pk.<KEY>'
```
=>
```
java.lang.RuntimeException: Cannot fetch best response if list is empty
        at com.graphhopper.GHResponse.getBest(GHResponse.java:49)
        at com.graphhopper.navigation.NavigateResource.doGet(NavigateResource.java:138)
```

**Comment by boldtrn** [comment]
Thanks for reporting this. 

Shouldn't this also happen for the main repository [here](https://github.com/graphhopper/graphhopper/blob/4c5d58946bb2a4df350e8d19c0ba9f2b4885bb2f/web-bundle/src/main/java/com/graphhopper/resources/RouteResource.java#L156) as well?

**Comment by boldtrn** [comment]
At least for [GHMaps](https://graphhopper.com/maps/?point=45.180396%2C5.711217&point=43.770625%2C11.255955&locale=de-de&vehicle=bike&weighting=fastest&elevation=true&turn_costs=false&use_miles=false&layer=Omniscale&algorithm=alternative_route&heading=307&ch.disable=true), this seems to be fine.

**Comment by karussell** [comment]
In gh-core repo we have a check in RouteResource to prevent this:

```
if (requestPoints.isEmpty())
    throw new IllegalArgumentException("You have to pass at least one point");
```

**Comment by boldtrn** [comment]
Not sure if I misunderstand the issue, but the url in the sample above has two requested points?

**Comment by karussell** [comment]
Sorry, I mixed the issue with something else. There must be no exception for any request. And as GHMaps seems to be fine the issue is probably here?

**Comment by boldtrn** [comment]
Mhm, I can't reproduce this error locally or on my test server. The error might be somehow connected to the bearings, if I remove the bearings, I don't get any result from the server:

`https://graphhopper.com/api/1/navigate/directions/v5/gh/cycling/5.711217,45.180396;11.255955,43.770625?overview=full&roundabout_exits=true&annotations=congestion%2Cdistance&voice_instructions=true&steps=true&geometries=polyline6&alternatives=true&banner_instructions=true&voice_units=metric&vehicle=bike&access_token=pk.<key>`

**Comment by karussell** [comment]
With bearings I get a http code 500 (internal server error). 

Without the bearings I still get {"message":""} with http code 422. So yes, something is strange here.

**Comment by karussell** [comment]
This is some internal problem we have to fix.
